"""empty message

Revision ID: 757fbe929a81
Revises: 
Create Date: 2020-12-15 02:43:20.173624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757fbe929a81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('firstname', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('firstname'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('lastname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
